- scripts/configure-hypervisor.sh
This script will ensure we use a single source of qemu build
options for the Kata Containers project.
Fixes: #7.
> qemu: Add script to generate hypervisor configure options.

- kernel/kata-linux-container.spec-template
This PR adds fixes to build kata packages for fedora 28.
> pkgs: Fix build for fedora 28.

- ccloudvm/README.md
- ccloudvm/kata-docker-xenial.yaml
Add templates to tests packages in VM.
> wip: ccloudvm: Add templates for kata containers.

- runtime/kata-runtime.spec-template
Fixes #59 
These are the bits for bash completion in the packaging repo.
Pending https://github.com/kata-containers/runtime/pull/378
> pkg: Add bash completion

- .ci/test.sh
- Makefile
- scripts/configure-hypervisor.sh
- scripts/lib.sh
- static-build/qemu/Dockerfile
- static-build/qemu/Makefile
- static-build/qemu/build-static-qemu.sh
Provide a way to build an static qemu with options required by kata. An static qemu will help to easily test kata or deploy using #65.
> pkg: Build an static qemu for kata

- release/tag_repos.sh
On each release we want to know the kernel config what was used.
Lets create a tag ${kata_verson}-kernel-config.
> release: tag: tag kernel build

- .ci/lib.sh
- .ci/run.sh
- .ci/setup.sh
- .gitignore
- Makefile
- snap/README.md
- snap/snapcraft.yaml.in
the yaml file is the recipe to build a snap image
with all Kata Containers components inside.
fixes #81
> snap: add yaml to build snap image

- Makefile
- release/Makefile
- release/README.md
- release/update-repository-version.sh
- release/update-repository-version_test.sh
Add script that will help to bump versions for all the projects.
Fixes: #49
> Update repository version

- .ci/lib.sh
- Makefile
- snap/README.md
Address code review of pr #82
fixes #88
> snap: improve README and Makefile

- kata-deploy/README.md
> Kata-deploy: scrub for grammar and typos in README

- obs-packaging/kata-containers-image/build_image.sh
- release/tag_repos.sh
- release/update-repository-version.sh
- scripts/lib.sh
After create tags create a github release.
After create the github release this can be edited to
add new assets or modify release notes.
> release: Create github release after create tag.

- .ci/lib.sh
> lib.sh: install_yq fails on ppc64le

- snap/README.md
Improve README by pointing to a specific sub-section 
in runtime repo that actually talks about the possibility 
of having multiple configurations files.
Fixes: #129
> snap: Improve README

- obs-packaging/Makefile
- obs-packaging/build_all.sh
- obs-packaging/build_from_docker.sh
- obs-packaging/create-repo-branch.sh
- obs-packaging/distros
- obs-packaging/kata-containers-image/build_image.sh
- obs-packaging/maintainers
- obs-packaging/scripts/obs-docker.sh
- obs-packaging/scripts/obs-pkgs.sh
- obs-packaging/scripts/pkglib.sh
- release/update-repository-version.sh
If want to create pkgs based in new branch, this script will create
all the empty repositories in OBS for each kata package.
Then we can point use the rest of scripts to push changes to this new repo.
> obs: create-repo-branch.sh: New script to create OBS repos.

- release/tag_repos.sh
release: tag: checkout to branch to tag.
Checkout to a target branch before create a tag.
We dont checkout for repos that does not have stable branches.
We want to do is just push the tags to master branch
since we don't maintain a seperate one.
The repos are:
osbuilder
packaging
ksm-throttler
Fixes: #163
> release: tag: checkout to branch to tag.

- release/runtime-release-notes.sh
Add script to generate release notes template
for runtime.
Will get the range of changes from two tags.
Get assets information from versions.yaml file.
Fixes: #169
> release: Add release notes automation.

- obs-packaging/kata-containers-image/update.sh
- obs-packaging/ksm-throttler/kata-ksm-throttler.spec-template
- obs-packaging/versions.txt
- release/kata-deploy-binaries.sh
- Add new fixes found creating Kata release  1.3.0-rc0
- Update versions file to new kata version.
> Kata 1.3 rc0

- obs-packaging/create-repo-branch.sh
Fix a minor typo in create-repo-branch 
script. 
Fixes:  #201
> create-repo-branch.sh: Fix a typo

- obs-packaging/gen_versions_txt.sh
> obs-packaging: Make golang hash dependency arch-specific

- obs-packaging/kata-containers-image/build_image.sh
Update variables needed by osbuilder.
Also fix query to get the initrd base OS.
Fixes: #210
> image: Fix image build

- snap/snapcraft.yaml.in
Add cpio to build-packages list since it's required to create initrd images
fixes #240
> snap: fix build error in launchpad

- kata-deploy/Dockerfile
> kata-deploy: update for 1.4 release

- obs-packaging/distros
- obs-packaging/qemu-lite/qemu-lite.spec-template
- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
Add changes needed to enable Fedora 29
\cc @chavafg @marcov @lsm5
> obs: enable fedora 29 

- obs-packaging/qemu-aarch64/patches/0001-qemu-gather-and-modification-of-the-whole-Eric-Auger.patch
Add Eric Auger's latest PCDIMM/NVDIMM patches for supporting nvdimm
on aarch64.
Fixes: #270
Signed-off-by: Hui Zhu <teawater@hyper.sh>
> obs-packaging: Add Eric Auger's latest PCDIMM/NVDIMM patches

- obs-packaging/gen_versions_txt.sh
- obs-packaging/runtime/kata-runtime.spec-template
- obs-packaging/versions.txt
Fix two issues and update versions.txt. I think this should fix the current obs build issues. Still waiting on obs confirmation though.
> Add 1.5.0-rc2 changes

- snap/1162-runtime.patch
- snap/1185-runtime.patch
- snap/snapcraft.yaml
Depends-on: https://github.com/kata-containers/runtime/pull/1162
> snap: release 1.5.0

- kata-deploy/kata-cleanup.yaml
- kata-deploy/kata-deploy.yaml
There was a bug in the script invocation in the YAML.  Fixed.
Fixes: #329
> kata-deploy: fix yaml example for install/remove commands

- snap/snapcraft.yaml
configure and start docker using sudo
fixes #355
> snap: use sudo to configure and start docker

- .ci/run.sh
- .ci/setup.sh
run all CI test to increase testing coverage on kernel config changes.
Fixes: #346
> ci: Run all CI test.

- kernel/README.md
Add documentation on how the kernel is tested and how changes could be
introduced.
Fixes: #344
> docs: kernel: Describe how to do kernel changes.

- CODEOWNERS
Add a CODEOWNERS file to get github auto review requests
for any .md file changes.
Fixes: #383
> ci: add CODEOWNERS to cover .md files

- snap/snapcraft.yaml
This version includes support for s390x
fixes #391
> snap: release 1.6.0-rc1

- CODEOWNERS
All doc changes need approval from the documentation team and all kernel
changes need approval from the kernel team.
Fixes #389.
> docs: Add CODEOWNERS file for doc and kernel changes.

- snap/snapcraft.yaml
bump snap version to 1.6.0
fixes #410
> snap: release 1.6.0

- snap/README.md
update architecture.md link, since it has moved to within the
design/ directory.
Fixes: #418
Signed-off-by: Gabi Beyer <Gabrielle.n.beyer@intel.com>
> doc: update architecture.md link

- scripts/configure-hypervisor.sh
Update configure hypervisor to support QEMU 3 and 4
fixes #419
> scripts: update configure-hypervisor.sh

- scripts/lib.sh
> kernel: Make sure local versions.yaml file from runtime get precedence

- .ci/run.sh
- .ci/setup.sh
build, install and test kata containers snap package.
fixes #428
> ci: run tests using kata snap

- .ci/run.sh
- snap/snapcraft.yaml
bump snap version to 1.7.0-alpha1
fixes #439
> snap: release 1.7.0-alpha1

- kata-deploy/README.md
- release/release.md
- snap/README.md
Resolve issues in the markdown files in this repo.
Fixes #435.
> docs: Fix markdown

- snap/README.md
Update Readme with command on 
how to remove snap after installing it. 
Fixes: #446
> Readme: Update readme with snap remove command

- Jenkinsfiles/release_pieline/Jenkinsfile
- Jenkinsfiles/release_pieline/bump.sh
- Jenkinsfiles/release_pieline/git_credential_cache.sh
Add pipeline to bump repos in Kata
> ci: Add bump release pipeline

- snap/README.md
Improve README and update with 
correct install snap command.
Fixes:  #469
> README: Update with correct install snap command

- obs-packaging/Dockerfile
- obs-packaging/build_from_docker.sh
- obs-packaging/create-repo-branch.sh
- obs-packaging/distros
- obs-packaging/download_image.sh
- obs-packaging/gen_versions_txt.sh
- obs-packaging/kata-containers-image/update.sh
- obs-packaging/linux-container/kata-linux-container.spec-template
- obs-packaging/scripts/obs-docker.sh
- obs-packaging/scripts/pkglib.sh
- obs-packaging/wait-obs.sh
- release/release.md
- release/update-repository-version.sh
- release/update-repository-version_test.sh
- scripts/lib.sh
This fixes are based on the work to create a release job in [azure pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)
Preview: 
https://dev.azure.com/vmjcarlos/kata-containers/_release
Fixes: #443
> azure-pipelines: Add fixes to allow automate release using azure pipelines.

- release/kata-deploy-binaries.sh
- static-build/nemu/Dockerfile
- static-build/nemu/Makefile
- static-build/nemu/build-static-nemu.sh
> nemu: add support for static build of nemu

- obs-packaging/linux-container/update.sh
Fix path to kernel patches.
Fixes: #505
> kernel: obs: fix kernel path

- kata-deploy/examples/test-deploy-kata-nemu.yaml
- kata-deploy/k8s-1.13/kata-nemu-runtimeClass.yaml
- kata-deploy/k8s-1.14/kata-nemu-runtimeClass.yaml
- kata-deploy/scripts/kata-deploy-docker.sh
- kata-deploy/scripts/kata-deploy.sh
Add support for nemu as part of kata-deploy
Fixes: #502
> kata-deploy: add nemu support

- snap/snapcraft.yaml
release kata containers 1.7.0
fixes #517
> snap: release 1.7.0

- kata-deploy/README.md
- kata-deploy/k8s-1.13/kata-fc-runtimeClass.yaml
- kata-deploy/k8s-1.13/kata-qemu-runtimeClass.yaml
- kata-deploy/k8s-1.13/runtimeclass-crd.yaml
> kata-deploy: fix k8s 1.13 example files

- release/release.md
Fix a typo in release doc.
Fixes: #564
> release.md: Fix a typo

- snap/snapcraft.yaml
update snap version
fixes #568
> snap: release 1.8.0-alpha0

- README.md
- kata-deploy/README.md
- release/release.md
Correct spelling mistakes and formatting issues.
Fixes: #571.
> docs: Fix typos and formatting

- static-build/qemu/Dockerfile
- static-build/qemu/build-static-qemu.sh
Apply the required patches when builing Qemu statically.
Fixes: #596.
> static-qemu: Apply qemu patches from this repo.

- release/update-repository-version.sh
Sometimes get logs could fail, for example
when a tag does not exit, instead of fail
just log the error in the PR.
Fixes: #609
> bump: Do not fail is not possible to get logs

- release/tag_repos.sh
After a rc0 is created the path to have an stable release starts, after that
any rc0 is to improve stabability and not more features are added. When it is
the projects is considered stable no more rc* are done.
Fixes: #611
> tag: Automatically create stable branch

- .ci/packaging/request_to_obs.sh
- obs-packaging/runtime/debian.rules-template
- static-build/qemu/Dockerfile
Fixes to bugs found in last release cycle.
> Packaging fixes for release 

- .ci/azure/pipelines/release.yml
add pipeline to integrate all  release jobs.
Signed-off-by: Jose Carlos Venegas Munoz <jcvenega@jcvenega-nuc.zpn.intel.com>
> release: add pipeline

- .ci/setup.sh
- snap/snapcraft.yaml
> snap: release 1.9.0-alpha0

- obs-packaging/distros_x86_64
Build packages for debian 10.
Fixes: #647
> obs: add debian 10

- obs-packaging/linux-container/debian.rules
- snap/snapcraft.yaml
Use master branch to test the snap in order to detect errors earlier
before releasing the next snap
fixes #663
> snap: use master branch to test the snap

- .ci/azure/pipelines/obs-packaging-ci.yml
- .ci/packaging/setup.sh
- scripts/lib.sh
Run depends-on for packaging CI.
Fixes: #683
> ci: azure: honor depends-on

- release/kata-deploy-binaries.sh
- static-build/qemu-virtiofs/Dockerfile
- static-build/qemu-virtiofs/Makefile
- static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
This adds support for virtio-fs on QEMU.
Fixes #699
> qemu: Enable qemu with virtio-fs 3.0

- release/kata-deploy-binaries.sh
Running for the first time the kata-deploy script can fail if hub
is not installed it, this will avoid this issue.
Fixes #728
> kata-deploy: Check that hub is installed

- release/release.md
Add requirement for the user to be added to the docker group.
Observed firecracker failing due to this.
Add fixes for typos and missing spaces.
Fixes #754
> doc: Fixes for release.md

- release/update-repository-version.sh
This replaces the alph to alpha on the message information.
Fixes #758
> release: Fixing message information

- release/tag_repos.sh
Now that all files have a VERSION we
can check if there is a bump for the file.
We can now tag all repos with the same kata version.
As all of them are branched and have a VERSION file.
Fixes: #748
> tags: Tag all repos with the same kata VERSION

- artifact-list.sh
- kata-deploy/Dockerfile
- kata-deploy/action/Dockerfile
- kata-deploy/action/action.yaml
- kata-deploy/action/entrypoint.sh
- kata-deploy/action/kubernetes-containerd.json
- kata-deploy/action/setup-aks.sh
- kata-deploy/action/test-kata.sh
- kata-deploy/examples/nginx-deployment-fc.yaml
- kata-deploy/examples/nginx-deployment-nemu.yaml
- kata-deploy/examples/nginx-deployment-qemu-virtiofs.yaml
- kata-deploy/examples/nginx-deployment-qemu.yaml
- obs-packaging/gen_versions_txt.sh
- release/kata-deploy-binaries.sh
- static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
Somewhat WIP.
Refactoring to simplify build scripts, make them usable in pipelined automation.
> Add actions release automation

- artifact-list.sh
- kata-deploy/Dockerfile
- obs-packaging/gen_versions_txt.sh
- release/kata-deploy-binaries.sh
- static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
refactoring portions of our release scripts to better suit for adding actions.
These are relatively straight forward, and submitted as a subset of https://github.com/kata-containers/packaging/pull/764
> Packaging cleaning prereq actions

- kata-deploy/scripts/kata-deploy.sh
- release/README.md
- release/release.md
- release/runtime-release-notes.sh
backport fixes for script typos and breakages in CRIO installation using kata-deploy.
> Stable 1.9 backport fixes

- snap/snapcraft.yaml
in order to make launchpad happy again, next changes are required:
* Install podman and cni plugings
* Use podman to build the rootfs or initrd image
* Depending on the architecture, build rootfs or initrd image
> snap: make launchpad happy again

- artifact-list.sh
- kata-deploy/Dockerfile
- kata-deploy/action/Dockerfile
- kata-deploy/action/action.yaml
- kata-deploy/action/entrypoint.sh
- kata-deploy/action/kubernetes-containerd.json
- kata-deploy/action/setup-aks.sh
- kata-deploy/action/test-kata.sh
- kata-deploy/examples/nginx-deployment-fc.yaml
- kata-deploy/examples/nginx-deployment-nemu.yaml
- kata-deploy/examples/nginx-deployment-qemu-virtiofs.yaml
- kata-deploy/examples/nginx-deployment-qemu.yaml
- obs-packaging/gen_versions_txt.sh
- release/kata-deploy-binaries.sh
- static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
Add action support to stable-1.9 branch
> Stable 1.9 add action support

- artifact-list.sh
- release/kata-deploy-binaries.sh
Unlike master, 1.9 branch supports NEMU VMM. Add necessary changes for
NEMU.
> actions: fixes for 1.9 branch

- obs-packaging/distros_x86_64
Build packages for ubuntu 19.04.
Fixes #776
> obs: Add ubuntu 19.04

- kata-deploy/scripts/kata-deploy.sh
Match indented CRI-O config fields.
Fix CRI-O qemu virtiofs runtime_path.
Fixes: #802
Signed-off-by: Brandon Wilson <brandon@coil.com>
Replaces #805
Overwriting may fail if there's whitespace in the existing table name or if the target key/value pair doesn't appear in the first line after the table name (https://github.com/kata-containers/packaging/issues/802#issuecomment-553739129)
> kata-deploy: add or overwrite runtimes in containerd config

- artifact-list.sh
- release/kata-deploy-binaries.sh
- static-build/cloud-hypervisor/build-static-clh.sh
- static-build/cloud-hypervisor/docker-build/Dockerfile
- static-build/cloud-hypervisor/docker-build/build.sh
- static-build/qemu-virtiofs/Dockerfile
Include cloud-hypervisor to Kata release tarball
Fixes: #792
> kata-static: Add cloud-hypervisor to tarball

- Makefile
- tests/Dockerfile/Dockerfile.in
- tests/run_obs_testing.sh
This will test that is possible to install the obs packages in different
distributions.
Fixes #621
> ci: Add obs testing for packaging

- kata-deploy/action/test-kata.sh
> kata-deploy: action: take updated yaml paths into account

- release/tag_repos.sh
We should start maintaining stable branches for the documentation
repo similar to other repos.
Fixes #1007
> release: Tag and fork documentation repo as part of release

- release/update-repository-version.sh
This PR adds the documentation repository for the update-repository-version
verification.
Fixes #1027
> release: Add documentation repository

- release/update-repository-version.sh
c536069 release: Add documentation repository
> backport fix 1.10

- obs-packaging/distros_x86_64
- obs-packaging/kata-containers-image/kata-containers-image.spec-template
- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
9e1ad10 obs: Update SLES version for packaging
82f5f40 obs: Remove OpenSUSE Leap 15.0 from obs generation
> backport fixes 1.10

- obs-packaging/create-repo-branch.sh
- obs-packaging/distros_x86_64
- obs-packaging/linux-container/kata-linux-container.spec-template
- obs-packaging/projectconfig
- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
Build packages for CentOS 8.
Fixes #1048
> obs: Add CentOS 8

- static-build/qemu/Dockerfile
update QEMU build dependencies to support QEMU 5
fixes #1058
> static-build: update QEMU build dependencies

- kata-deploy/README.md
Fix some typo in kata-deploy Readme
Fixes: #991
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
> kata-deploy: Fix typo

- .ci/packaging/setup.sh
- kernel/patches/5.4.x/0002-ACPI-Always-build-evged-in.patch
- obs-packaging/qemu-vanilla/debian.rules-template
- scripts/configure-hypervisor.sh
- snap/snapcraft.yaml
- static-build/qemu-virtiofs/Dockerfile
- static-build/qemu/Dockerfile
Add needed fixes to enable stable virtiofs in kata CI
> ci: Fixes for virtiofs stable 
