kata-containers/packaging

- .pullapprove.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Add the pullapprove configuration file.
- Add the standard Code of Conduct and contributing docs.
> Bootstrap repo

- scripts/configure-hypervisor.sh
Qemu 2.11 does not support --disable-static flag, add a condition
to only use it for qemu 2.7 or older.
Fixes: #11.
> qemu: does not use --disable-static for qemu 2.11

- scripts/configure-hypervisor.sh
PR #12 inadvertently removed the required tags for two of the qemu
config options.
Partially fixes #13.
> scripts: Re-add tags for hypervisor config script

- release/README.md
- release/tag_repos.sh
Add helper script to tag repos.
- Check all repos are in the same version
- Create annotated tags
- Push tags to the repos
> release: Add script to tag repos

- .ci/run.sh
- .ci/setup.sh
- .ci/static-checks.sh
- .ci/teardown.sh
- Makefile
- release/tag_repos.sh
- release/tag_repos_test.sh
Add base scripts to setup, run, and teardown tests
for ci.
Fixes: #21
> ci: Add initial CI scripts

- scripts/configure-hypervisor.sh
We can only set disable fno-semantic-interposition if the
gcc used to build qemu is 5.3 or newer.
CentOS provides an older gcc, then we need to not enable this
option if it is the case.
Fixes #32.
> qemu: disable fno-semantic-interposition for old gcc

- .gitignore
- kernel/update.sh
- qemu-lite/debian.series
- qemu-lite/patches/0001-memfd-fix-configure-test.patch
- qemu-vanilla/debian.series
- qemu-vanilla/patches/0001-memfd-fix-configure-test.patch
- scripts/pkglib.sh
Allow build qemu for fedora 28 and ubuntu 18.04
> Fix qemu build in distros with new glibc versions.

- qemu-lite/qemu-lite.spec-template
- qemu-vanilla/qemu-vanilla.spec-template
Build qemu without librados. This allows build qemu in OBS.
Fixes: #37
> qemu: rhel: Remove librados to allow build.

- kernel/kata-linux-container.dsc-template
- kernel/kata-linux-container.spec-template
- kernel/update.sh
- runtime/update.sh
Add the version of config and patches we are using in a package.
Kernel version before:
4.14.22-128
Now:
4.14.22.1-128
Fixes: #45
> pkg: kernel: Add kernel config version to pkg version.

- Makefile
Package generation test is taking more than 20 minutes to build a dockerfile. Skip until find a way to fix the issue.
Fixes: #68
> ci: Skip non working test.

- release/tag_repos.sh
Make sure the osbuilder VERSION file is updated before tag
Also, sort repos alphabetically.
> tag_repos: Make sure osbuilder is updated.

- kata-deploy/kata-cleanup.yaml
- kata-deploy/kata-deploy.yaml
Now that initial files for kata-deploy have merged, we
have an initial image on dockerhub.  s/egernst/katadocker
Fixes: #100
> kata-deploy: update to use katadocker container image

- scripts/configure-hypervisor.sh
a few qemu options generated by configure-hypervisor.sh weren't suitable for arm64, leading compilation err. lib-configure-hypervisor-aarch64.sh will create specific qemu options for arm64.
Fixes: #92
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
Signed-off-by: Wei Chen <Wei.Chen@arm.com>
> ci: refine qemu-options for arm64

- obs-packaging/kata-containers-image/build_image.sh
- scripts/lib.sh
This PR reworks the existing script to create images for a release.
It creates a tarball with more explicit names. 
- The tarball includes the architecture that was used to build the tarball.
- Useful to publish the image in agent repository.
- Added usage help message.
- Build master by default but allow to define a tag for agent and osbuilder version.
> image build: Improve image generation

- obs-packaging/kata-containers-image/build_image.sh
shift $((OPTIND-1)) can be unsafe.To prevent unwanted
word-splitting all parameter expansions should be
double-quoted. Use the safe form for the command:
shift "$((OPTIND-1))"
Fixes: #109
> build_image.sh: OPTIND prevent unwanted word-splitting

- scripts/lib.sh
When tmp_dir is not set and lib.sh is sourced
could lead to fail.
Fix: #116
> ci: Fix ci when tmp_dir is not set.

- release/tag_repos.sh
Fix variable name that breaks the script when creating releases.
Fixes: #121
> tag_repos.sh: fix typo

- snap/snapcraft.yaml.in
Kernel building fails as part of "make snap" as
the kernel config file is renamed from ppc64le_kata_kvm_4.14.x
to powerpc_kata_kvm_4.14.x
Fixes:  #127
> snapcraft.yaml: Use the correct powerpc kernel config name

- snap-build/README.md
The #usage part of README talks about
cross building snap images for all "supported
architectures" not "supported images". 
Fixes: #131
> snap-build: Fix a typo in README

- snap/README.md
The Integration with docker link in
README is broken. Fix it.
Fixes: #133
> snap: Fix broken link in README

- kata-deploy/Dockerfile
- kata-deploy/kata-cleanup.yaml
- kata-deploy/kata-deploy.yaml
update dockerfile to 1.2.0
Update yaml to use explicit versions, since 1.2.0 is introducing changes in how the tarball is formatted.
> Kata deploy 1.2 dockerfile

- release/tag_repos.sh
- release/update-repository-version.sh
- release/update-repository-version_test.sh
The current scripts to automate part of release
will do PRs and tags based in master.
This will not longer the only one case, kata will 
maintain multiples braches.
Add options to decide what branch will be used for releases.
> release: support release branches.

- kata-deploy/kata-cleanup.yaml
- kata-deploy/kata-deploy.yaml
- kata-deploy/scripts/install-kata-containerd.sh
- kata-deploy/scripts/install-kata-crio.sh
- kata-deploy/scripts/remove-kata-containerd.sh
- kata-deploy/scripts/remove-kata-crio.sh
automated and improved tarball has slightly different format.  Update kata-deploy to make use of the new dockerfile (which uses this tarball).
> Kata deploy 1.2 update

- obs-packaging/Dockerfile
When pcre-tools is installed before build/obs-service-tar_scm
then "build-mkbaselibs-20180629-289.1.noarch.rpm" is installed
as a dependency but OBS repo does not have that rpm. So install
"pcre-tools" at the end and Dockerfile builds fine on ppc64le.
Also, make zypper install verbose by adding "-v"
Fixes:  #139
> Dockerfile: Install pcre-tools later to avoid dependency issue

- obs-packaging/build_from_docker.sh
Currently, since GOARCH is not set inside
a Dockerfile, it by default always pick's up amd64.
Pass GOARCH as build-args to fix it.
Fixes #148
> obs-packaging: Build and run Dockerfile based on GOARCH

- obs-packaging/scripts/pkglib.sh
osc checkout fails silently. Make osc co
verbose as it is helpful for debugging. 
Fixes: #150
> obs-packaging: scripts: make osc checkout verbose

- obs-packaging/build_all.sh
qemu-lite is required to be packaged only
for amd64 arch. Skip it for all other
architectures.
Fixes: #152
> obs-packaging: Skip packaging qemu-lite for non-amd64 arch

- obs-packaging/scripts/pkglib.sh
pkglib.sh uses BUILD_ARCH and DEB_ARCH which are
by default not set and hence take the value of
x86_64 and amd64 respectively. Make this
architecture specific.
Fixes: #154
> obs-packaging: set BUILD_ARCH, DEB_ARCH arch specific

- release/tag_repos.sh
The osbuilder version file wont be the same if
we tag a stable branch. But we still want to tag
the HEAD of osbuilder to do reproducible builds of
a Kata branch.
Fixes: #158
> release: dont check osbuilder VERSION file.

- obs-packaging/Makefile
- obs-packaging/gen_versions_txt.sh
- obs-packaging/kata-containers-image/build_image.sh
- obs-packaging/kata-containers-image/update.sh
- obs-packaging/scripts/pkglib.sh
- release/publish-kata-image.sh
- scripts/lib.sh
Fix image generation, instead of use the source code in the
host we clone it all the time to make sure we use a fresh
and clean agent repository when we generate the image.
Make sure that the agent commit id is the correct before
push to github or OBS.
Fixes: #166
> Check agent commit id when image is generated.

- obs-packaging/gen_versions_txt.sh
Replace non-valid character from kata version.
This will make the version compatible with rpmbuild.
Fixes: #179
> packaging: Replace `-` for `~`

- Makefile
"make clean" errors out if snap/snapcraft.yaml file
does not exsist and the recipe for target 'clean'
fails. Avoid this my adding a "-f" option to rm to
have a clean state.
Fixes: #187
> Makefile: Do not error out on "make clean"

- obs-packaging/scripts/obs-docker.sh
unable to prepare context, unable to evaluate symlinks
in context path when building target test-packaging-tools
on ppc64le.
Fixes: #189
> obs-packaging: Fix "make test-packaging-tools" failure

- obs-packaging/runtime/update.sh
The kata-runtime spec file, when specifying a `Requires:` version for
qemu-lite and qemu-vanilla, does not include the "+git.<commit hash>"
part.
As a result of this, versions of kata-runtime and qemu installed on a
system using RPM package management may be inconsistent.
Fixes: #193
> obs-packaging: fix runtime qemu-* required version

- obs-packaging/Makefile
make -f .obs-packaging/Makefile clean fails with
"No such file or directory" even after deleting the
files returned by find. Fix it by using -prune.
Fixes: #203
> obs-packaging: Makefile: Use -prune to delete a directory

- obs-packaging/build_all.sh
- obs-packaging/scripts/obs-pkgs.sh
This script creates empty repos in OBS
but qemu-lite repo is not needed/used
for non-amd64 archs. Hence skip it.
Fixes: #206
> create-repo-branch: Skip repo branch qemu-lite for non-amd64

- obs-packaging/linux-container/kata-linux-container.spec-template
Linux-container OBS packaging for ppc64le
fails as the spec file is x86 specific for
kernel build and install process.
Fixes: #224
> ppc64le: Fix linux-container OBS packaging

- snap/snapcraft.yaml.in
Add libfdt-dev as build dependency because of qemu requires it in ppc and arm.
fixes #97
> snap: fix build errors

- release/runtime-release-notes.sh
Include in the release notes the kubernetes version that
has been tested with the release.
Fixes: #235.
> release: Add k8s compatible version to release notes

- obs-packaging/gen_versions_txt.sh
- obs-packaging/runtime/debian.rules-template
- obs-packaging/runtime/kata-runtime.spec-template
- Skip golang version checking when building on OBS.
- Remove the hardcoded golang version in the version generation script.
Fixes: #242
>  golang version requirements for OBS packaging

- obs-packaging/build_all.sh
Improve the usage output, and add the ability to specify a list of projects to process as extra arguments.
Before:
```
$ ./build_all.sh
missing branch
Usage:
build_all.sh <kata-branch>
```
After:
```
$ ./build_all.sh
ERROR: missing branch
Usage:
build_all.sh [-h | --help] <kata-branch> [PROJ1 PROJ2 ... ]
Generate OBS packages sources for the kata projects, based on branch
kata-branch.
build_all.sh processes all the kata projects by default; alternatively you can
specify a subset of the projects as additional arguments.
Environment variables:
PUSH        When set, push the packages sources to the openSUSE build
service.
LOCAL       When set, build the packages locally.
```
> Build all improvements

- obs-packaging/ksm-throttler/debian.control-template
- obs-packaging/ksm-throttler/kata-ksm-throttler.dsc-template
- obs-packaging/proxy/debian.control-template
- obs-packaging/proxy/kata-proxy.dsc-template
- obs-packaging/runtime/debian.control-template
- obs-packaging/runtime/kata-runtime.dsc-template
- obs-packaging/shim/debian.control-template
- obs-packaging/shim/kata-shim.dsc-template
Remove the redundant dh-modaliases package as a build requirement
for deb packages. This allows to build packages for the Debian distro.
I tested this change a OBS branch and builds for all Ubuntu and Debian are fine.
Fixes: #249
Related: #247
> obs-packaging: remove dh-modaliases deb requirement

- release/kata-deploy-binaries.sh
The kata-shim Makefile is changed and we should not set libexecdir
anymore.
Fixes: #257 
/cc @clarklee92 @grahamwhaley @marcov
> release: fix kata-deploy-binaries.sh install command

- obs-packaging/build_all.sh
- obs-packaging/gen_versions_txt.sh
- obs-packaging/versions.txt
Align the content of versions.txt with the latest 1.4.0 version released on OBS.
Detect misalignments of versions between the content of versions.txt
file and the version found in the VERSION file in the git branch being
released on OBS.
Fixes #255
> Update versions.txt content and detect versions misalignment

- obs-packaging/linux-container/debian.rules
- obs-packaging/linux-container/kata-linux-container.spec-template
- obs-packaging/linux-container/kata-multiarch.sh
- obs-packaging/linux-container/update.sh
Update the kernel package to allow building for multiple architectures with
a single set of sources.
Changes:
- Add kernel configs for all architectures
- Detect at runtime the correct target architecture and kernel
compressed image location. This is done  with the script kata-multiarch.sh.
Note that debian control files still need to be updated to handle Multi-Arch,
so that they are not tied to the architecture on which
`linux-container/update.sh` is run.
Fixes: #262
> obs-packaging: multi-arch kernel build support

- snap/snapcraft.yaml.in
Right golang version is installed before building kata-containers, skip go
version check to avoid including extra build dependencies.
fixes #265
> snap: skip go version check

- obs-packaging/distros
- Add Debian 9 (#289)
- Remove EOL (#279)
- Add recent openSUSE (Leap 15.0 and Tumbleweed).
> Update list of stable release distros

- obs-packaging/gen_versions_txt.sh
Fix version compare when specifying a pre-release version in
versions.txt. This is needed because kata on git uses strict semver,
while kata RPM packages uses ~ in place of - for PATCH version, to
allow RPM version comparison to work properly.
Fixes: #285
> obs-packaging: support comparisons of pre-releases versions

- .gitignore
- Makefile
- snap/snapcraft.yaml
In some build systems like launchpad is not possible to run neither
custom commands or hooks, hence build a snap image with `make snap` is
not feasible, to deal with this limitation, the final snapcraft.yaml
is part of the repository and all packages versions are read from versions.yaml
in the runtime repository.
fixes #305
> snap: don't use make snap to build the snap

- Makefile
- release/kata-deploy-binaries.sh
- static-build/firecracker/Makefile
- static-build/firecracker/build-static-firecracker.sh
Start packaging the supported version of firecracker.
Requires: https://github.com/kata-containers/runtime/pull/1104
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> Firecracker: Add support for firecracker packaging

- obs-packaging/ksm-throttler/kata-ksm-throttler.spec-template
- obs-packaging/linux-container/debian.rules
- obs-packaging/runtime/debian.rules-template
- obs-packaging/runtime/kata-runtime.spec-template
- obs-packaging/versions.txt
- release/kata-deploy-binaries.sh
- release/runtime-release-notes.sh
https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support                                                                                                                                                               
The wiki says that a wrapper is part of the release tarball,  `make install`                                                                                                                                                                                                    
from runtime is not doing it, add workaround until this is added as an official wrapper. …
> release: 1.5.0 fixes

- scripts/configure-hypervisor.sh
This commit adds the s390x specific build flags to the configure-hypervisor.sh
Fixes: #324
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
> s390x: add support to build qemu

- ccloudvm/kata-docker-xenial.yaml
Update the kata install commands to point to the correct repository URL.
Fixes: #326
> ccloudvm: update kata install URL

- release/release.md
Document flow to create a release based in the tools
from this repository.
Fixes: #207
> docs: Document release process - tools.

- kata-deploy/scripts/kata-deploy.sh
kata-deploy inserts 'manage_network_ns_lifecycle' into crio.conf without any
prior checks and if there is a previous entry in the file, this becomes a
duplicate causing crio service restart issues. This patch addresses that
particular scenario.
> kata-deploy: Check crio conf before update

- .ci/lib.sh
- snap/snapcraft.yaml
This allows running packaging CI scripts on s390x to create snap image.
For completeness, snap-build files also created.
Fixes #341
Signed-off-by: Tuan Hoang <tmhoang@linux.vnet.ibm.com>
> snap: add support for s390x

- kata-deploy/kata-deploy.yaml
- kata-deploy/scripts/kata-deploy.sh
Add support for the v2-shim integration with containerd. This registers
a runtimeClass named 'kata', utilizing the containerd-shim-kata-v2
binary.
This change adds volume mounts (hopefully temporarily) for
/usr/local/bin, as containerd requires the shim binary be within the
existing path.
Fixes: #323
> kata-deploy: add support for v2 shim

- snap/snapcraft.yaml
new kernel, new dependencies. Add bison, build-essential and flex as
kernel dependencies
fixes #395
> snap: launchpad: Add missing kernel dependencies

- obs-packaging/linux-container/debian.rules
- obs-packaging/linux-container/kata-linux-container.spec-template
Override build user+host+timestamp
to make kata-linux-container package builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of the variable.
`SOURCE_DATE_EPOCH` is unset atm in the .spec file case because no changelog is there to allow rpm to parse the date from it.
Fixes part of issue #394
This PR was done while working on reproducible builds for openSUSE.
> Override build user+host+timestamp

- kata-deploy/scripts/kata-deploy.sh
Rather than add the config for kata-qemu and kata-fc unconditionally,
the script now checks if the runtime config exists.
If it exists, then do not chnage the path for the runtime.
The user may have configured this to a specific path for testing
local chnages.
Fixes #374
> kata-deploy: Add runtime config for crio if it does not exist

- README.md
We use a packagecloud OSS account for package hosting.
As part of the arrangement with packagecloud we need to
credit them and add a link back to https://packagecloud.io
on our website and project README.
This was added to the kata-containers repository's README,
but it is also probably appropriate to add it to the packaging
README as well.
Signed-off-by: Thierry Carrez <thierry@openstack.org>
> Credit packagecloud for package hosting

- snap/snapcraft.yaml
Former snap configuration `snapcraft.toml` install `qemu-lite` for all platforms, which isn't applicable on aarch64. We need `qemu-aarch64` of specific version and extra patches.
> snap-aarch64: modify qemu-related info for arm64

- obs-packaging/linux-container/kata-linux-container.spec-template
- obs-packaging/versions.txt
- scripts/lib.sh
Fix issues found in Kata release 1.5.1
Note: The  ubuntu 16.04 failed on OBS, I confirm that golang 1.11 does not work with this ubuntu version.
https://github.com/kata-containers/packaging/issues/264
> Release 1.5.1

- .github/stale.yml
To assist in tracking older issues/PRs, let's add a tool for marking
issues and pull requests as being stale after 60 days of inactivity. A
stale issue/PR will be closed after 7 days of being marked stale.
This is functionality, a GitHub application from probot (and hosted by in this configuration), and only has visibility into GitHub issue/PR's metadata, and ability to comment / close.  
I'd be happy with using this, and we can migrate to use GitHub actions once more widely available (beta)
> stale: add initial configuration for stale probot

- kata-deploy/scripts/kata-deploy.sh
When writing our runtime configs to crio.conf, let's add some
whitespace and comments to make it clearer, and fit in with the
rest of the crio.conf file.
Fixes: #412
> kata-deploy: crio.conf: Add some whitespace and comments

- kata-deploy/examples/test-deploy-kata-qemu.yaml
We no longer use the TrustedSandbox style annotations now we
have moved to the RuntimeClass method of choosing a runtime.
Drop the remaining Trusted items from the examples.
Fixes: #403
> kata-deploy: remove Trusted annotations from examples

- kata-deploy/k8s-1.13/kata-fc-runtimeClass.yaml
- kata-deploy/k8s-1.13/kata-qemu-runtimeClass.yaml
- kata-deploy/k8s-1.14/kata-fc-runtimeClass.yaml
- kata-deploy/k8s-1.14/kata-qemu-runtimeClass.yaml
Add the yaml for kata RuntimeClasses. It is useful to
include this explicitly, rather than just having it in the docs.
Also, this feature has transitioned from alpha to beta from k8s 1.13
to 1.14. Hence maintain separate yamls for these versions.
We should eventually move towards maintaining separate versions
for all our yaml files for the k8s versions that we support.
Fixes #444
> kata-deploy: Add runtimeclass yaml to kata-deploy

- scripts/configure-hypervisor.sh
modify configure-hypervisor.sh to support Qemu 4 and enable `malloc-trim`
for memory optimization.
fixes #459
> scripts: support Qemu 4

- scripts/configure-hypervisor.sh
Change weird condition to check qemu >=3.1
Add comment explaining the malloc-trim option.
fixes #462
> scripts: improve configure-hypervisor.sh

- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
Simplify qemu rpm list  files using wildcard
this will help to build different qemu versions
without change all the list of files.
- Exclude not needed binaries.
Kata does not use helper binaries, and
4.0 build has a missing qemu-ga by default,
excluding files does not fail if the file exist or not.
Fixes: #464
> qemu-vanilla: pkg: Fix build for qemu 4.0

- snap/snapcraft.yaml
On ppc64le, qemu installed inside a snap image
is qemu-system-ppc64, but referred in config.toml
as qemu-system-ppc64le.
Fixes #467
> snap: Container fails to start on ppc64le

- obs-packaging/qemu-vanilla/patches/0001-9p-removing-coroutines-of-9p-to-increase-the-I-O-per.patch
- obs-packaging/qemu-vanilla/patches/0002-migration-add-capability-to-bypass-the-shared-memory.patch
Add kata specific patches for qemu 4.0:
* 9p optimization
* vm-templating patch
fixes #471
> qemu-vanilla: add patches required in qemu 4.0 to run kata containers

- obs-packaging/kata-containers-image/build_image.sh
- obs-packaging/kata-containers-image/kata-containers-image.spec-template
- obs-packaging/kata-containers-image/update.sh
- obs-packaging/ksm-throttler/_service-template
- obs-packaging/ksm-throttler/kata-ksm-throttler.dsc-template
- obs-packaging/ksm-throttler/kata-ksm-throttler.spec-template
- obs-packaging/linux-container/kata-linux-container.spec-template
- obs-packaging/proxy/_service-template
- obs-packaging/proxy/kata-proxy.dsc-template
- obs-packaging/proxy/kata-proxy.spec-template
- obs-packaging/qemu-lite/qemu-lite.spec-template
- obs-packaging/qemu-lite/update.sh
- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
- obs-packaging/qemu-vanilla/update.sh
- obs-packaging/runtime/_service-template
- obs-packaging/runtime/kata-runtime.dsc-template
- obs-packaging/runtime/kata-runtime.spec-template
- obs-packaging/runtime/update.sh
- obs-packaging/scripts/pkglib.sh
- obs-packaging/shim/_service-template
- obs-packaging/shim/kata-shim.dsc-template
- obs-packaging/shim/kata-shim.spec-template
Do not add  the `commit id` to the package version, this help to install an specific kata version when
using repositories that provide different  versions like packageclould.
- Define runtime deps with the exact set of versions
of a release.
- remove obs release counter,  we already use our counter for rpms and debs and dnf  gets confused
if we used. 
Fixes: #453
> packages: Remove git hash from version

- snap/snapcraft.yaml
Debian convention is to call it endian little rather than little endian, 
hence ppc64el rather than ppc64le. So if build system is debian,
then snap image built on it will fail to set the correct qemu binary
name.
Fixes: #473
> snapcraft: Consider debian ppc64el convention

- obs-packaging/download_image.sh
- obs-packaging/scripts/pkglib.sh
- release/publish-kata-image.sh
- release/release.md
- scripts/lib.sh
lib.sh: dont use readonly on sourced files.
release: publish: image: fix commit length
pkglib: fix sourced path
docs: release: add step to generate version file before image.
lib.sh: dont do readonly on sourced files.
release: publish: image: fix commit length
pkglib: fix sourced path
docs: release: add step to generate version file before image.
> release:  fixes for 1.5.5

- Jenkinsfiles/release_pieline/bump.sh
- release/Makefile
update-repository-version script no longer expects the repository name,
but just the version and the target branch. Modify associated Makefile
and jenkins pipeline files to adapt to that change.
Fixes: #443
> bump-repos: Make associated files adapt to newer bump script

- release/runtime-release-notes.sh
Fix markdown link to point to the rigth documentation.
Fixes: #1516
> docs: release-notes: Fix markdown link

- kata-deploy/README.md
Change the kata-deploy doc to get rid of code-snippets
and instead include instructions to apply the provided
RuntimeClass yaml according to the k8s version being used.
Fixes #457
> kata-deploy: Change the kata-deploy doc to use yaml files

- kata-deploy/scripts/kata-deploy.sh
If the containers deployed by kata-deploy.yaml have had to restart, lack of overwrite here causes a benign error message to appear since the nodes already have `katacontainers.io/kata-runtime=true` label. Having a overwrite here means that we don't get the following error message in the logs and prevent the deployment to fail needlessly:
error: 'katacontainers.io/kata-runtime' already has a value (true), and --overwrite is false
> Allow kata-deploy containers to restart gracefully

- obs-packaging/runtime/debian.control-template
- obs-packaging/runtime/kata-runtime.dsc-template
Strict dependencies guarantees that an older version of the runtime will
not be installed together with a more recent version of the other kata
packages.
This complements commit e73473f.
Fixes: #508
> runtime: specify strict dependencies Debian package

- obs-packaging/kata-containers-image/build_image.sh
build_from_docker.sh fails to read from versions.yaml as 
yq is not installed.
Fixes: #514
> build_image: Install yq before get_from_kata_deps

- release/tag_repos.sh
If anyone repository fails to upload to github a new release, this
script cannot be re-run as is today. It would nice for the script to
check if github has been updated with a release already and proceed with
the rest of the repositories if that is true.
Fixes: #519
> release: Allow re-tries of tagging and github releases

- obs-packaging/distros
Add fedora 30 to the list of packages to build.
Fixes: #523
> obs: build: enable fedora 30

- obs-packaging/runtime/update.sh
Make qemu-lite as requirement only
for x86_64 arch
Fixes: #529
> runtime: qemu-lite required only for x86_64 arch

- scripts/lib.sh
the versions.yaml file in runtime carries the information on all the
components we use and ship with kata. It would be nice to have the CI
test the newer versions when the file is changed and CI is triggered.
The current code always fetches from the master tree from github and
that does not help to validate version changes before it lands in the
tree.
> ci: always use the versions from the local repository for CI

- obs-packaging/scripts/pkglib.sh
Set debian Power arch as ppc64el not
ppc64le in debian.rules and .dsc files
Fixes: #533
> obs-packaging: Set debian Power arch as ppc64el

- static-build/nemu/Dockerfile
- static-build/nemu/build-static-nemu.sh
NEMU needs to be built statically as the current default release will
not work for all distros. Given we are doing that, it would be nice to
test it in our CI also the same way. This change is to aid with that.
Fixes: #521
> nemu: build nemu for CI

- scripts/lib.sh
Creating Kata packages fails
due to "Makefile:58: *** target pattern
contains no '%'.  Stop" error. Fix it.
Fixes: #539 
> lib.sh: Pass right parameters to build image

- static-build/nemu/build-static-nemu.sh
- static-build/qemu/build-static-qemu.sh
normal users might not have the correct permissions to run
docker without sudo.
In addition, as docker will run with sudo, fix permissions
on the qemu and nemu files.
Fixes: #544.
> static-builds: run docker commands using sudo

- obs-packaging/build_all.sh
- obs-packaging/runtime/update.sh
- obs-packaging/scripts/obs-pkgs.sh
- obs-packaging/scripts/pkglib.sh
When specifying a "Depends: (= VERSION" match in deb packages, the full
"VERSION" needs to be specified, including any trailing release number.
A more relaxed alternative to this, without knowing the full version
of dependencies, is to specify each dependency as both ">= VERSION" and
"<< VERSION+1".
This fixes a regression introduced in: 63413814
Fixes: #531
> runtime: fix strict "= VERSION" dependencies for deb pkg

- obs-packaging/runtime/update.sh
Fix regression introduced with e6dac82 related to kata-runtime package
generation.
Fixes: #548
> runtime: fix regression in package generation

- cmd/kata-pkgsync/Gopkg.lock
- cmd/kata-pkgsync/Gopkg.toml
- cmd/kata-pkgsync/vendor/github.com/mlafeldt/pkgcloud/distros.go
Update pkgcloud pacakge to add Fedora 30 to the list of distros
supported by to Packagecloud.
Shortlog since last vendoring of github.com/mlafeldt/pkgcloud:
926cf4b Update list of distros (Add Fedora 30)
Fixes: #546
> kata-pkgsync: vendor: update pkgcloud to add Fedora 30

- scripts/configure-hypervisor.sh
Disable PAM authentication: it's a feature used together with VNC access
that's not used in Kata.
See QEMU commit 8953caf for more details on PAM auth.
Fixes: #550
> QEMU: disable PAM authentication (used for VNC access)

- obs-packaging/download_image.sh
commit length is needed to download the image.
> download_image: source pkglib to get commit length.

- obs-packaging/distros_x86_64
The runtime package is faling to build due to
compatiblity issues  with gcc + golang because
the redhat version provided in OBS old.
Disable temporarily to allow release CI  work.
> obs: distros: disble redhat build for x86_64

- scripts/configure-hypervisor.sh
AVX2 are x86 specific extensions that should only be enabled for x86_64
targets.
Fixes: #558
> QEMU: only enable AVX2 for x86_64

- scripts/lib.sh
Recent change to always build tools from the local repository if the
script is run in a CI environment fails during a release build as the
variable ${CI} is not initialized. This fix addresses that issue.
Fixes: #537
> release: initialize CI variable in lib.sh

- obs-packaging/runtime/debian.control-template
- obs-packaging/runtime/kata-runtime.dsc-template
- obs-packaging/runtime/update.sh
For RPM packages (but not for DEBs), OBS does not use the release number
provided in the spec file, hence, when specifying a
`Requires: package = version-release` dependency, it's not possible to know
in advance the correct release number until that reuired package
is built.
Note that omitting the release number works for RPM packages but not for DEB.
This fixes/complements e6dac82
Fixes: #563
> runtime: omit the release number in RPM Requires:

- obs-packaging/gen_versions_txt.sh
- release/publish-kata-image.sh
- scripts/lib.sh
Add `--head` option to use the head of the branch instead of the kata
version to generated the hashes for the packages. With this new option
kata packages can be generated using the latest commit on master.
fixes #566
> obs-packaging/gen_versions: add --head option

- static-build/qemu/build-static-qemu.sh
Use the tag of qemu from `versions.yaml` instead of the
version number if the version does not exist in the references
of the repository.
Fixes: #587.
> static-build: qemu: use tag if version doesn't exist

- static-build/qemu/Dockerfile
- static-build/qemu/build-static-qemu.sh
Instead of always having `prefix` hardcoded to `/opt/kata`,
change the script to be able to take the value from an
enviroment variable.
Fixes: #589.
> static-build: qemu: be able to change prefix variable

- release/kata-deploy-binaries.sh
- static-build/firecracker/Makefile
- static-build/firecracker/build-static-firecracker.sh
Add jailer binary to kata-deploy. It allows us to enable jailer
with firecracker.
Fixes: #593
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> kata-deploy: Add jailer binary

- .ci/azure/pipelines/obs-packaging-ci.yml
Add simple yaml definition to run job in azure pipelines.
Fixes: #480
> ci: Add intial pipeline to test OBS package generation

- static-build/firecracker/build-static-firecracker.sh
Latest firecracker has moved the generated binaries to a new
location. Update the scripts to use the new location.
Fixes: #599
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> kata-deploy:  Update scripts to support firecracker 0.17.0

- obs-packaging/runtime/debian.rules-template
- obs-packaging/runtime/kata-runtime.spec-template
We are looking to deprecate qemu-lite. As a first step,
let's go ahead and make qemu-vanilla (4.0) the default VMM.
> packages: update default VMM to qemu-vanilla

- obs-packaging/Dockerfile
The image tag opensuse:leap not longer exist
use the the new image format.
Fixes: #615
> obs: dokcer: update leap image base.

- release/tag_repos.sh
- release/tag_repos_test.sh
The main purpose is that this script will be used to verify
that VERSION among the components are equal before merging the runtime.
Fixes #613
Depends-on: github.com/kata-containers/runtime#1858
> ci: Enable check VERSION among the components without the runtime

- scripts/configure-hypervisor.sh
QEMU >= 4.1 uses libssh not libssh2
fixes #627
> scripts: update configure-hypervisor script to support QEMU 4.1

- snap/snapcraft.yaml
bc is required to build the snap in launchpad
fixes #635
> snap: add bc to build-packages

- obs-packaging/distros_x86_64
Seems that OBS now fixed issues with ubuntu,
add it back.
Fixes: #607
> distros: add ubuntu 16.04 back

- scripts/configure-hypervisor.sh
quote `>= 4.1` to avoid bash redirects `echo`'s output to a
new file named `=`
fixes #652
> scripts: fix detection of qemu 4.1

- release/kata-deploy-binaries.sh
- static-build/scripts/kata-configure-docker.sh
Create a script that will be added to the `kata-static-${version}-${arch}.tar.xz` file and which can be either run directly by the user to configure Docker, or can be run indirectly by the `kata-manager` script.
Fixes: #648.
> release: Add a Docker config script for static Kata

- obs-packaging/kata-containers-image/debian.rules-template
- obs-packaging/kata-containers-image/kata-containers-image.spec-template
In order to improve the security of Kata, nothing should be able to modify
the images. It would be really bad if a malicious container or process
modified them.
fixes #631
> obs-packaging: install images as read-only files

- obs-packaging/scripts/obs-docker.sh
- obs-packaging/wait-obs.sh
The job to wait for packages are built is failing randomly.
Seems that sometimes the command is not retuning and expected
out out and may be mask by the
while osc pr | grep; done
This probably can fail at osc pr but because it failed at
osc and not grep we consider is working.
First query the result, if fail the script will stop,
if not then try to find the string state=building.
Additionally, check for failed jobs in the same query to
stop the job earlier.
Fixes: #665
> obs: wait: Fix error to detect building job

- scripts/configure-hypervisor.sh
- static-build/nemu/Dockerfile_cross
- static-build/nemu/Makefile
- static-build/nemu/build-static-nemu.sh
This patch enable cross-compile nemu for arm64 in container
on x86 host.
fixed: #577
Signed-off-by: Jianyong Wu  <jianyong.wu@arm.com>
@jodh-intel @bergwolf @ganeshmaharaj @grahamwhaley @Pennyzct
> nemu: enable compile nemu for arm64 on x86 host

- static-build/nemu/build-static-nemu.sh
Fix `arch` assignment and define `Dockerfile` variable to avoid
usage of unbound variables.
fixes #671
> static-build: fix nemu static-build

- kernel/README.md
Fix the instructions in the README guide
when setting up kernel source code. 
Fixes:  #673
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
> kernel: Update README with right instructions

- qemu/patches/4.0.x/0003-memory-backend-file-nvdimm-support-read-only-files-a.patch
- snap/snapcraft.yaml
Use the rootfs image by defult since performance is better,
smaller memory footprint and boot time.
fixes #667
> snap: support rootfs image

- obs-packaging/distros_x86_64
Upgrade openSUSE Leap version from 42.3 to the latest 15.1, since 42.3
version is now discontinued.
Fixes: #637
> OBS: upgrade openSUSE Leap version

- qemu/patches/4.1.x/0001-9p-removing-coroutines-of-9p-to-increase-the-I-O-per.patch
- qemu/patches/4.1.x/0002-memory-backend-file-nvdimm-support-read-only-files-a.patch
Add patches for qemu 4.1.x
fixes #679
> patches: add patches for qemu 4.1.x

- release/kata-deploy-binaries.sh
kata deploy script setup a new GOPATH to pull
a fresh environment to install kata. This script
was using the local kernel install script and not the
one in the new environment
Fixes: #706
> kata-deploy: use proper kernel install script

- release/kata-deploy-binaries.sh
kata deploy script setup a new GOPATH to pull
a fresh environment to install kata. This script
was using the local kernel install script and not the
one in the new environment
Fixes: #706
> kata-deploy: use proper kernel install script (backport)

- obs-packaging/distros_x86_64
To allow test packages in azure.
Fixes: #661
> obs: distros: enable SLE12-SP4

- static-build/firecracker/build-static-firecracker.sh
Removes `--vsock` flag when building Firecracker since
the flag was removed as vsock is enabled by default.
Also update the path where the binaries are placed.
Fixes: #739.
> static-build: Fix build for Firecracker v0.18

- qemu/patches/virtiofsd/0001-add-time-to-seccomp.patch
- static-build/qemu-virtiofs/Dockerfile
time syscall on seccomp is needed to be able to build
virtiofsd successfully.
This patch is currently not availabe upstream, so lets
add it until it becomes available.
In addition, apply qemu/patches/virtiofsd/0001-add-time-to-seccomp.patch
to be able to build virtiofsd statically.
> static-build: Add patch that adds time to virtiofsd seccomp

- release/update-repository-version.sh
- check if a bump goes from alpha to rc0. The tag automation will create branches if there is a rc0 tag,
better check we dont miss it.
- version all  repos. Add version to all kata repos.
> Release 1.9 improvements

- release/kata-deploy-binaries.sh
We dont need to install nemu in the static tarball.
Fixes #750
> deploy: Skip installing nemu

- release/kata-deploy-binaries.sh
Tarball is missing to provide a wrapper for qemu-virtiofs
Fixes: #756
> kata-deploy: Add qemu-virtiofs wrapper

- kata-deploy/scripts/kata-deploy.sh
- We need an entry of `kata-qemu-virtiofs` on the
containerd configuration file.
- In addition we need to add `kata-qemu-virtiofs` to the
shim list, so that the wrapper is created for shimv2.
- Fix indentation issues on `kata-deploy.sh` file.
Fixes: #760.
> kata-deploy: Add qemu-virtiofs to containerd configuration

- kata-deploy/scripts/kata-deploy.sh
Use correct key for the kata-qemu-virtiofs runtime class definition
in the crio configuration file.
Fixes: #771.
> kata-deploy: fix qemu-virtiofs entry on crio configuration

- release/README.md
- release/release.md
- release/runtime-release-notes.sh
For better reading, re-orginize the `release/README.md`
and fix a typo in `runtime-release-notes.sh`.
Fixes: #769.
> release: Fix typos and organization issues

- static-build/nemu/build-static-nemu.sh
Make the build context of nemu to be consistent with qemu.
Fixes #752
> nemu: Fix docker build context for nemu to support older docker versions

- kata-deploy/action/test-kata.sh
Should have been fixed before merge. Reference upstream instead of fork
of Kata.
Fixes #789
> kata-deploy: action: reference kata-containers instead of fork

- kata-deploy/scripts/kata-deploy.sh
Append to file if container/config.toml already exists.
double brackets ftw!
Fixes: #307
> kata-deploy: don't remove pre-existing containerd

- release/update-repository-version_test.sh
Bump test fails because Kata  version at this moment is alfa and
only bumps from alpha to rc0 are allowed. Just use rc0 as use-case
for all, there is not any other constrain at the moment.
Fixes: #795
> CI: Fix bump test

- release/kata-deploy-binaries.sh
With the previous syntax, literal value was being assigned to
kata_version.
Fixes: #793
> release: Fix bug in evaluation kata_version.

- obs-packaging/create-repo-branch.sh
The repos of the CI builds are not used anywhere so let's be friendly to
the OBS infrastructure and do not publish them.
Signed-off-by: Ralf Haferkamp <rhafer@suse.com>
> obs: Disable repo-publishing for CI builds

- static-build/scripts/kata-configure-docker.sh
Fix bug in the `kata-configure-docker.sh` script which assumed `/etc/docker/` existed by default.
Fixes: #800
> scripts: Fix static build docker config script

- qemu/patches/virtiofsd/0002-libvhost-user-Fix-the-VHOST_USER_PROTOCOL_F_SLAVE_SE.patch
- static-build/qemu-virtiofs/Dockerfile
In order to get both QEMU and Cloud-Hypervisor working with virtio-fs, a
patch needs to be applied in order to fix a libvhost-user bug.
Fixes #810
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> qemu-virtiofs: Add one patch to fix libvhost-user

- obs-packaging/wait-obs.sh
In case a package in obs is excluded ie no longer being built,
do not wait for it to be built. Wait as long as there are packages
being built or blocked on others to be built.
Fixes #815
> obs: Do not wait on excluded packages

- obs-packaging/ksm-throttler/kata-ksm-throttler.dsc-template
- obs-packaging/proxy/kata-proxy.dsc-template
- obs-packaging/runtime/kata-runtime.dsc-template
- obs-packaging/shim/kata-shim.dsc-template
It seems that to build ksm-throttler, proxy, runtime and shim OBS packages
for ubuntu 19.04, we need fakeroot to avoid having unresolvable packages. This adds that dependency so we can build them.
Fixes #776
> obs: Add fakeroot dependency for ubuntu 19.04

- obs-packaging/wait-obs.sh
We need to fail when we have unresolvable packages as they are not build
correctly.
Fixes #820
> obs: Failed when we have unresolvable packages

- release/update-repository-version_test.sh
Bump test fails because Kata  version at this moment is alfa and
only bumps from alpha to rc0 are allowed. Just use rc0 as use-case
for all, there is not any other constrain at the moment.
Fixes: #795
> [backport] CI: Fix bump test

- kernel/build-kernel.sh
- release/kata-deploy-binaries.sh
- static-build/firecracker/build-static-firecracker.sh
- static-build/nemu/Dockerfile
- static-build/nemu/build-static-nemu.sh
- static-build/qemu-virtiofs/Dockerfile
- static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh
- static-build/qemu/Dockerfile
- static-build/qemu/build-static-qemu.sh
These changes introduced for github actions need to be backported so that we can use single latest github action workflow yaml for both 1.9 and 1.10 branches.
Additionally changes have been introduced for nemu, that has been deprecated for 1.10.
> Backport tarball renaming changes related to github actions to 1.9

- kata-deploy/action/setup-aks.sh
Recent runs of setting up aks with github workflows shows that a timeout
of 5m is not always sufficent fot aks control plane to come up.
Increase this from 5m to 10m.
Fixes #839
> kata-deploy: Increase the wait timeout for control plane to come up

- kata-deploy/action/setup-aks.sh
Recent runs of setting up aks with github workflows shows that a timeout
of 5m is not always sufficent fot aks control plane to come up.
Increase this from 5m to 10m.
Fixes #839
> kata-deploy: Increase the wait timeout for control plane to come up (Backport)

- obs-packaging/wait-obs.sh
We need to check for broken packages at the obs-wait script.
Fixes #492
> obs: Check for broken packages

- kata-deploy/action/test-kata.sh
I am seeing tests fail at times waiting for label cleanup. Let's improve
the error message when this fails, and give the control plane a bit more
time, to improve stability of this test.
Fixes: #846
> kata-deploy: improve debug message, longer cleanup timeout

- kernel/build-kernel.sh
Checkout tag for packaging repo based on env variable NEW_VERSION
or kata_version with kata_version taking precedence.
With this, we checkout to the right version of packaging repo before
applying kernel patches.
Fixes #849
> release: Checkout right version of kernel patches(backport to 1.8)

- kernel/build-kernel.sh
Checkout tag for packaging repo based on env variable NEW_VERSION
or kata_version with kata_version taking precedence.
With this, we checkout to the right version of packaging repo before
applying kernel patches.
Fixes #849
> release: Checkout right version of kernel patches(backport to 1.9)

- obs-packaging/wait-obs.sh
2b0d946 obs: Check for broken packages
e59f03c obs: Failed when we have unresolvable packages
7979c6d obs: Do not wait on excluded packages
> Backport fixes for 1.9

- kernel/build-kernel.sh
- release/kata-deploy-binaries.sh
NEW_VERSION may be unbound whereas kata_version should be defined
following manual release process docs and while using github actions.
Use kata_version instead to checkout correct version of patches.
Check if kata_version is not empty before doing so,
as the release may be triggered for master as well.
Fixes #857
> kernel: checkout patched based on kata_version

- qemu/patches/4.1.x/0002-memory-backend-file-nvdimm-support-read-only-files-a.patch
Modify existing patch to include EACCES condition to account for files
that do not have write access to be used as a memory backend.
With this not-only files on a read-only filesystem, but files without
write access on a read-write filesystem can be used as a memory
backend in qemu.
This will alow the image to be used read-only by a rootless user as
well.
Fixes #870
> qemu: Patch qemu to support image without write access.

- snap/snapcraft.yaml
Use `sort -V -r` to sort versions and use a regexp to
make sure the tag has the right format, since not all
tags follow Semantic Versioning 2.0.0.
fixes #872
> snap: fix how latest stable version is obtained

- obs-packaging/distros_x86_64
- tests/run_obs_testing.sh
Fedora 28 has come to end of life status which makes not possible to
retrieve the repositories while performing an update. This PR removes
this distro with this version so we not longer create and test obs packages
for fedora 28.
Fixes #879
> obs: Remove fedora 28 obs packages

- static-build/cloud-hypervisor/docker-build/build.sh
If we want to run the build.sh by using a user this is failing by saying
that `failed to dial gRPC: cannot connect to the Docker daemon...
/var/run/docker.sock: connect: permission denied`. This PR fixes that issue.
Fixes #889
> kata-static: Add sudo while building cloud hypervisor docker image

- qemu/patches/4.2.x/0001-9p-removing-coroutines-of-9p-to-increase-the-I-O-per.patch
- qemu/patches/4.2.x/0002-memory-backend-file-nvdimm-support-read-only-files-a.patch
- static-build/qemu.blacklist
spapr-rtas.bin is no longer part of qemu 4.2.0, so it should be removed from
blacklist.
fixes #877
> fixes for qemu 4.2.0

- release/tag_repos.sh
Now CI depends on this repository, needed to make work stable
branches starting stable-1.10
Fixes: #894
> release: tag and branch kata-containers repository

- tests/run_obs_testing.sh
Now that we have obs packages for ubuntu 19.04, we should add it in the
testing script.
Fixes #884
> obs: Add ubuntu 19.04 testing

- kata-deploy/action/action.yml
- kata-deploy/action/setup-aks.sh
- kata-deploy/action/test-kata.sh
- kata-deploy/scripts/kata-deploy.sh
- code cleanup (typos, etc)
- improve how label removal check is carried out
- pull packaging repositoy down if doesn't exist, rather than curl'ing.
Fixes: #909
> backport: testing: stability improvements for kata-deploy

- kata-deploy/action/test-kata.sh
If already exit do not clone it, but fetch.
Fetch will keep repository is up-to-date before checkout.
Fixes: #911
> actions: check for packaging before clone

- release/update-repository-version.sh
kata-containers is now part of the release processs.
Lets update the version for that repository.
Fixes: #905
> release: bump kata-containers repository

- kata-deploy/action/setup-aks.sh
Use absolute path to kubeconfig to allow kubectl use it.
Fixes: #915
> release: use absolute path for kubeconfig

- scripts/lib.sh
yq is not exploding anchors anymore and requiere an extra flag.
Add flag to fix CI.
Fixes: #934
> lib: yq: explode anchors to get real value of image values

- obs-packaging/linux-container/_service-template
- obs-packaging/linux-container/debian.rules
- obs-packaging/linux-container/kata-linux-container.spec-template
Kernel build for packages got broken after upgrade, this add needed
changes to build again.
Fixes #924
> pkgs: fix kernel build

- release/tag_repos.sh
This repo triggers the github action to create release tarballs.
It looks for release tags in other repos. So tag this repo
last to make sure tags have been created on other repos.
Fixes #947
> release: tag the kata-containers/kata-contaners repo last

- scripts/lib.sh
yq is not exploding anchors anymore and requiere an extra flag.
Add flag to fix CI.
Fixes: #934
> Backport: lib: yq: explode anchors to get real value of image values

- kata-deploy/scripts/kata-deploy.sh
Now crio.conf has some kata entries in by default, but commented
out and without the runtime_path elements to them, our deploy
script gets a little confused and fails to add the kata-qemu
elements to the config.
This is because the grep spots the commented out lines, and tries
to, unsuccessfully, update the matching runtime_path elements, that
don't actually exist.
Improve this by matching only uncommented config lines, so now the
script sees that the runtime is not really configured already, and
instead of trying to edit/update it, will place a entry at the
end of the file.
Fixes: #928
> kata-deploy: improve logic for crio.conf runtime additions

- obs-packaging/distros_x86_64
- tests/run_obs_testing.sh
Now that ubuntu 19.04 and fedora 29 has come EOL, we should remove the generation of
the obs generation and testing for ubuntu 19.04.
Fixes #953
> obs: Remove obs packages and testing for ubuntu 19.04 and fedora 29

- tests/Dockerfile/FedoraDockerfile.in
- tests/run_packages_testing.sh
This will test the kata-containers packages that are available on
Fedora 31 to see that they are working properly.
Fixes #951
> test: Test for kata-containers packages on Fedora 31

- obs-packaging/qemu-vanilla/debian.rules-template
- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
- scripts/configure-hypervisor.sh
- snap/snapcraft.yaml
- static-build/qemu-virtiofs/Dockerfile
- static-build/qemu/Dockerfile
Enable libpmem to support PMEM when running under Kubernetes.
see https://github.com/kata-containers/runtime/issues/2262
According to QEMU's nvdimm documentation: When 'pmem' is 'on' and QEMU is
built with libpmem support, QEMU will take necessary operations to guarantee
the persistence of its own writes to the vNVDIMM backend.
fixes #958
> scripts/qemu: enable libpmem

- scripts/configure-hypervisor.sh
- snap/snapcraft.yaml
Not all architectures have support for libpmem.
Enable libpmem only for x86_64
fixes #965
> scripts: enable libpmem only for x86_64

- obs-packaging/distros_ppc64le
Fedora versions 28 and 29 has come EOL, we should update the generation
of obs packages but now for Fedora 30.
Fixes #963
> obs: Update obs packages for ppc64le

- Jenkinsfiles/release_pieline/Jenkinsfile
1. For the git clone operation, `sh` step in a single line would suffice.
2. Provide directory context using `dir`, this avoids having to provide the complete path to each and every script, that are in that folder, while executing.
Signed-off-by: Ramanathan Muthaiah <rus.cahimb@gmail.com>
> ci: Provide source directory path for script execution

- .ci/azure/pipelines/obs-packaging-ci.yml
- .ci/azure/pipelines/release.yml
- .ci/setup.sh
- Jenkinsfiles/release_pieline/bump.sh
- ccloudvm/kata-docker-xenial.yaml
- snap/README.md
- snap/snapcraft.yaml
- static-build/cloud-hypervisor/docker-build/Dockerfile
- static-build/qemu-virtiofs/Dockerfile
- static-build/qemu/Dockerfile
- static-build/scripts/kata-configure-docker.sh
- tests/run_obs_testing.sh
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Fixes #970
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> pod : optimization Some debian package manager tweaks

- obs-packaging/distros_x86_64
OpenSUSE Leap 15.0 has reached EOL, this PR removes the obs generation.
Fixes #980
> obs: Remove OpenSUSE Leap 15.0 from obs generation

- .github/workflows/kata-deploy-test.yaml
Let's change the kata-deploy github action trigger from:
'/test kata-deploy'
to
'/test-kata-deploy'
which will hopefully reduce the number of false triggers caused when
we issue the 'normal' CI runs that are triggered by other
'/test xxxx' phrases.
Fixes: #971
> actions: change trigger phrase for kata-deploy action

- obs-packaging/distros_x86_64
- obs-packaging/kata-containers-image/kata-containers-image.spec-template
- obs-packaging/qemu-vanilla/qemu-vanilla.spec-template
Currently for our CI, we have SLES 15 SP1, this PR updates the current obs
version to match with our current testing.
Fixes #983
> obs: Update SLES version for packaging

- scripts/configure-hypervisor.sh
Update configure-hypervisor.sh to support QEMU 5.0.
fixes #989
> scripts: update configuration script to support QEMU 5.0

- kata-deploy/scripts/kata-deploy.sh
fixes #996
The default k3s `containerRuntimeVersion` takes the form of ```containerd://1.3.3-k3s2```.
The `awk` was stripping away the `k3s` portion before checking if it was a k3s containerd.
> kata-deploy: fix k3s containerd check

- tests/Dockerfile/FedoraDockerfile.in
- tests/run_packages_testing.sh
For obs and running the packages testing in Fedora, we need to remove
the performing of doing an update as it is hit by
https://github.com/kata-containers/runtime/issues/2580. This is needed
to unblock the errors in the testing.
Fixes #1001
> tests: Remove performing updates in Fedora dockerfile

- scripts/lib.sh
stable-1.10 branch uses old version of yq that doesn't support
the `-X` flag, so we need to remove it.
Fixes: #1011.
> stable-1.10: yq: remove `-X` flag

- scripts/configure-hypervisor.sh
--enable-pie is not compatible with --static option for qemu building.
Without this patch, it will report a configure error during static building:
ERROR: static and pie are mutually incompatible
Fixes: #982
Signed-off-by: Jia He <justin.he@arm.com>
> scripts: Disable pie for qemu when static building

- scripts/lib.sh
stable-1.9 branch uses old version of yq that doesn't support
the `-X` flag, so we need to remove it.
Fixes: #1011.
> backport: stable-1.9: yq: remove `-X` flag

- obs-packaging/scripts/pkglib.sh
obs ci for linuxcontainer will fail when apply patch set which have
dependency within. so patch set should be made in order before feed
to apply.
Fixes: #1015
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
@grahamwhaley @jodh-intel
> obs: let patch set in order before apply them

- scripts/lib.sh
We need to use the same yq version in stable-1.10 across all
the repositories.
In the future, we should check the installed version of yq and
use (or not) the corresponding flag.
Fixes: #1022.
> tools: use yq 2.3.0 for stable-1.10

- scripts/lib.sh
We need to use the same yq version in stable-1.10 across all
the repositories.
In the future, we should check the installed version of yq and
use (or not) the corresponding flag.
Fixes: #1022.
(cherry picked from commit 6fe4d781fd452b2e8c8470f31390d5b1bfde7eef)
> backport: tools: use yq 2.3.0 for stable-1.9

- release/tag_repos.sh
- release/update-repository-version.sh
0763f2a release: bump kata-containers repository
bf0baf9 release: Tag and fork documentation repo as part of release
> backport 1.10 fixes

- obs-packaging/distros_x86_64
Debian 10 has been broken for a while but CI started
to detected recently.
Remove package until find a way to build it.
Fixes: #1052
> pkgs: Remove debian 10

- static-build/qemu.blacklist
- static-build/qemu/Dockerfile
Update ubuntu version to 20.04, due to the following linkage errors
is not possible to build QEMU 5 on ubuntu 18.04.
```
libmount.a(libmount_la-fs.o): In function `__mnt_fs_set_source_ptr':
(.text+0x9b1): undefined reference to `blkid_parse_tag_string'
libmount.a(libmount_la-tab.o): In function `mnt_table_find_source':
(.text+0x1dbf): undefined reference to `blkid_parse_tag_string'
libmount.a(libmount_la-utils.o): In function `mnt_tag_is_valid':
(.text+0x618): undefined reference to `blkid_parse_tag_string'
libmount.a(libmount_la-cache.o): In function `mnt_free_cache':
(.text+0x834): undefined reference to `blkid_put_cache'
libmount.a(libmount_la-cache.o): In function `mnt_cache_read_tags':
(.text+0xa24): undefined reference to `blkid_new_probe_from_filename'
(.text+0xa3d): undefined …
```
> static-build: build qemu on ubuntu 20.04

- .ci/lib.sh
- .ci/static-checks.sh
- .travis.yml
- cmd/kata-pkgsync/cli/main.go
Set up the config file and .ci subdir files to enable Travis to perform static
checks on PRs to this repo.
> CI: enable Travis static checks

- kata-deploy/scripts/kata-deploy.sh
CRI has a v2 schema that seems to be the default in a lot of
containerd installations. It uses a "long" form for the plugin
id in the TOML config file.
Fixes #881. I couldn't find any tests for this script, and I 
don't really have time to learn how to build the whole project,
but I did test this change with my config.toml and it worked.
> Detect v2 schema and use correct long form of cri plugin

- qemu/patches/5.0.x/0001-9p-removing-coroutines-of-9p-to-increase-the-I-O-per.patch
- qemu/patches/5.0.x/0002-memory-backend-file-nvdimm-support-read-only-files-a.patch
qemu: add kata patches for QEMU 5
Add the following patches for QEMU 5:
* memory-backend-file/nvdimm: support read-only files as memory-backends
* 9p: removing coroutines of 9p to increase the I/O performance
fixes #1064
> qemu: add kata patches for QEMU 5

- kata-deploy/k8s-1.18/kata-runtimeClasses.yaml
As of 1.18 this feature is Beta. We will need this applied if we are
running utilizing sandbox cgroups only (this should really be default).
We'll want to iterate on the most appropriate values going forward, but this is a safe starting point.
Fixes: #995
Signed-off-by: Eric Ernst <eric@amperecomputing.com>
> kata-deploy: add PodOverhead to RuntimeClasses

- kata-deploy/scripts/kata-deploy-docker.sh
Add an ACRN runtime ('kata-acrn') to the Docker configuration (daemon.json)
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
> kata-deploy: add ACRN runtime to Docker configuration

- snap/snapcraft.yaml
The static libraries needed to build QEMU 5.0.0 are not available in
Ubuntu 18.04 and due to some bugs in the azure ubuntu 20.04 image, it's not
possible to build QEMU 5 statically
fixes #1090
> snap: build QEMU 4.1.1 not 5.0.0

- kata-deploy/scripts/kata-deploy.sh
For privieleged containers, all host devices are passed to
container. We have done work in crio and containerd to define a
scope of privileged in Kata to prevent this from happening.
Add this as the default as this falls under a best practice to follow
with Kata.
Note that if this flag has been already defined, then this change
does not override it.
Fixes #1087
> kata-deploy: Add default privileged_without_host_devices

- kata-deploy/scripts/kata-deploy.sh
In case of containerd, not all annotations are passed down to the OCI
layer. We need to configure "pod_annotations" field for a runtime class.
This field is a list of annotations that can be passed by Kata as OCI
annotations. Add this as default configuration with kata-deploy.
Fixes #1093
> kata-deploy: Add containerd configuration to support kata annotations.

- snap/snapcraft.yaml
Ubuntu 20.04 is required to build statically QEMU 5.
fixes #1107
> snap: build snap using Ubuntu 20.04

- .github/workflows/snap.yaml
Move snap CI to github actions, since it needs ubuntu 20.04 to build
and there is no such image in the current jenkins-azure CI system
fixes #1092
> snap: move snap CI to github actions

- obs-packaging/distros_ppc64le
- obs-packaging/distros_x86_64
We can rely on distros packages for SUSE, openSUSE, Fedora, and CentOS.
For RHEL, users are better relying on CentOS packages as a workaround instead of relying on the community version of the packages.
> Stop building for distros that already support kata

- kata-deploy/README.md
Parent PR:
https://github.com/kata-containers/packaging/pull/992
Issue:
https://github.com/kata-containers/kata-containers/issues/591
The issue this fixes is in the main kata-containers repo, not packaging. We're not sure how exactly to format the PR properly.
> [forward port]: kata-deploy: Fix typo #591

- snap/snapcraft.yaml
In order to avoid `unmet dependencies` error in the CI,
the python version must be specified in the yaml.
fixes #1163
> snap: specify python version

- snap/snapcraft.yaml
yq major releases are not backward compatible, install the same
major version used in the CI to avoid conflics building the kata
components.
We should update yq when the CI updates it, not before.
fixes #1186
> snap: tag yq version

- snap/snapcraft.yaml
yq major releases are not backward compatible, install the same
major version used in the CI to avoid conflics building the kata
components.
We should update yq when the CI updates it, not before.
fixes #1186
> [backport] snap: tag yq version

- static-build/cloud-hypervisor/build-static-clh.sh
Try to pull the cloud-hypervisor from its release page first. If it
failed, we build the clh binary from scratch.
Fixes: #1191
Signed-off-by: Bo Chen <chen.bo@intel.com>
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
> static-build: Pull the release binary of cloud-hypervisor first
